# Generated by Django 4.2.27 on 2025-12-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_commission_rate_shop_current_cycle_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='commission_rate',
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
