# Generated by Django 4.2.27 on 2025-12-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded')], default='pending', max_length=20),
        ),
    ]
