# Generated by Django 4.2.27 on 2025-12-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
    ]
