# Generated by Django 4.2.27 on 2026-01-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_cancellation_reason_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='soft_block',
            field=models.BooleanField(default=False, help_text='Flag for potential RTO/Fraud'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meesho_order_id',
            field=models.CharField(blank=True, help_text='Supplier Order ID', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending_cod', 'Pending COD Collection'), ('received_from_meesho', 'Payment Received from Meesho'), ('failed_rto', 'Failed (RTO)')], default='pending_cod', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='meesho_url',
            field=models.URLField(blank=True, help_text='Internal reference for sourcing'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('forwarded', 'Forwarded to Shop'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rto', 'Returned to Origin (RTO)'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='VorionMart', max_length=200),
        ),
    ]
