# Generated by Django 4.2.27 on 2026-01-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customer_soft_block_order_is_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_count',
            field=models.PositiveIntegerField(default=0, help_text='Total orders placed'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rto_count',
            field=models.PositiveIntegerField(default=0, help_text='Total RTOs'),
        ),
        migrations.AddField(
            model_name='customer',
            name='successful_deliveries',
            field=models.PositiveIntegerField(default=0, help_text='Total delivered orders'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending_cod', 'Pending COD Collection'), ('received', 'Payment Received'), ('failed_rto', 'Failed (RTO)')], default='pending_cod', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('confirmed', 'Confirmed'), ('ordered_from_meesho', 'Ordered from Meesho'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rto', 'Returned to Origin (RTO)'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
