# Generated by Django 4.2.27 on 2026-01-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Maximum Retail Price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='our_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Our Selling Price to Customer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price from Meesho/Supplier', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
