# Generated by Django 4.2.27 on 2026-01-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_mrp_product_our_price_product_supplier_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='product',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='current_cycle_start',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='default_commission',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
