# Generated by Django 4.2.27 on 2026-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_subscription_commission_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('confirmed', 'Confirmed'), ('ordered_from_meesho', 'Ordered from Meesho'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rto', 'Returned to Origin (RTO)'), ('cancelled', 'Cancelled'), ('returned', 'Returned (Customer)')], default='pending', max_length=20),
        ),
    ]
