# Generated by Django 4.2.27 on 2026-01-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_returned_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('confirmed', 'Confirmed'), ('ordered_from_meesho', 'Ordered from Meesho'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rto', 'Returned to Origin (RTO)'), ('cancelled', 'Cancelled'), ('returned', 'Returned (Customer)')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.order')),
            ],
            options={
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['changed_at'],
            },
        ),
    ]
