# Generated by Django 4.2.27 on 2026-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_supplier_orderforwardlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending_cod', 'Pending COD Collection'), ('pending', 'Pending'), ('received', 'Payment Received'), ('received_from_meesho', 'Received from Meesho'), ('paid', 'Paid'), ('failed_rto', 'Failed (RTO)'), ('refunded', 'Refunded')], default='pending_cod', max_length=30),
        ),
    ]
