# Generated by Django 4.2.27 on 2026-01-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('confirmed', 'Confirmed'), ('forwarded', 'Forwarded'), ('processing', 'Processing'), ('ordered_from_meesho', 'Ordered from Meesho'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rto', 'Returned to Origin (RTO)'), ('cancelled', 'Cancelled'), ('returned', 'Returned (Customer)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('confirmed', 'Confirmed'), ('forwarded', 'Forwarded'), ('processing', 'Processing'), ('ordered_from_meesho', 'Ordered from Meesho'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rto', 'Returned to Origin (RTO)'), ('cancelled', 'Cancelled'), ('returned', 'Returned (Customer)')], max_length=20),
        ),
    ]
