# Generated by Django 4.2.27 on 2026-01-21 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_product_sold_count_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage of profit shared with the partner (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
