# Generated by Django 4.2.27 on 2026-01-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_shop_commission_rate_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
