# Generated by Django 4.2.27 on 2026-03-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_expand_supplier_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('b2b_ecommerce', 'Online B2B E-commerce Store'), ('local_shop', 'Local Shop'), ('single_product_wholesaler', 'Single Product Wholesaler'), ('multi_product_seller', 'Multiple Product Seller'), ('retailer', 'Retailer'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='shop',
            name='source_platform',
            field=models.CharField(blank=True, help_text='e.g. IndiaMART, Meesho, Shopify, local market', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='sourcing_partner',
            field=models.ForeignKey(blank=True, help_text='Partner who sourced or onboarded this shop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_shops', to='api.partner'),
        ),
        migrations.AddField(
            model_name='shop',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
