# Generated by Django 4.2.27 on 2026-03-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_shop_contact_person_shop_notes_shop_shop_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sourcing_partners',
            field=models.ManyToManyField(blank=True, help_text='All partners involved in sourcing this shop', related_name='attributed_shops', to='api.partner'),
        ),
    ]
