# Generated by Django 4.2.27 on 2026-04-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_sitesetting_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='google_merchant_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_merchant_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='last_google_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
