import requests
import logging
import json
import re
from django.conf import settings

logger = logging.getLogger('api')

class GeminiBlogService:
    """Service to handle AI blog generation using Google Gemini API."""
    
    def __init__(self):
        self.api_key = getattr(settings, 'GEMINI_API_KEY', None)
        self.model = "gemini-2.0-flash"
        self.url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"

    def _generate_text(self, prompt):
        import time
        if not self.api_key:
            return None, "Gemini API Key not configured in settings."

        data = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.7,
                "topK": 40,
                "topP": 0.95,
                "maxOutputTokens": 4096,
            }
        }

        max_retries = 5
        for attempt in range(max_retries):
            try:
                response = requests.post(self.url, json=data, timeout=90)
                
                # Handle 429 Rate Limit with exponential backoff
                if response.status_code == 429:
                    wait_time = min(2 ** attempt * 3, 60)  # 3s, 6s, 12s, 24s, 48s
                    logger.warning(f"Gemini API 429 (Rate Limited). Attempt {attempt + 1}/{max_retries}. Retrying in {wait_time}s...")
                    time.sleep(wait_time)
                    continue
                
                # Handle temporary 503 Overload
                if response.status_code == 503:
                    wait_time = min(2 ** attempt * 2, 30)
                    logger.warning(f"Gemini API 503 (Service Unavailable). Attempt {attempt + 1}/{max_retries}. Retrying in {wait_time}s...")
                    time.sleep(wait_time)
                    continue
                
                response.raise_for_status()
                result = response.json()
                
                if 'candidates' in result and result['candidates']:
                    text = result['candidates'][0]['content']['parts'][0]['text']
                    return text, None
                else:
                    return None, f"No content generated by AI: {result}"
            except requests.exceptions.HTTPError as e:
                if response.status_code == 403:
                    logger.error(f"Gemini API 403 Forbidden - API key may be invalid or API not enabled.")
                    return None, "API key is invalid or the Generative Language API is not enabled. Check Google Cloud Console."
                if attempt == max_retries - 1:
                    logger.error(f"Gemini API Error after {max_retries} attempts: {str(e)}")
                    return None, str(e)
                logger.warning(f"Gemini API Attempt {attempt + 1} failed: {str(e)}. Retrying...")
                time.sleep(2)
            except Exception as e:
                if attempt == max_retries - 1:
                    logger.error(f"Gemini API Error after {max_retries} attempts: {str(e)}")
                    return None, str(e)
                logger.warning(f"Gemini API Attempt {attempt + 1} failed: {str(e)}. Retrying...")
                time.sleep(2)
        
        return None, "Failed after multiple retries"

    def generate_keywords(self, product):
        """Step 1: Generate SEO keywords for a product."""
        prompt = f"""
        Generate 10 SEO keywords for this product:
        Product Name: {product.name}
        Description: {product.description[:500]}
        Category: {product.category.name if product.category else 'General'}
        Location: India
        Focus: High buying intent keywords.
        Return as a comma-separated list without any extra text.
        """
        text, error = self._generate_text(prompt)
        if error:
            return [], error
        
        # Clean up keywords
        keywords = [k.strip() for k in text.split(',')]
        return keywords[:10], None

    def generate_outline(self, product, keywords):
        """Step 2: Generate SEO blog outline."""
        keywords_str = ", ".join(keywords)
        prompt = f"""
        Create a comprehensive SEO blog outline for this product:
        Product: {product.name}
        Keywords: {keywords_str}
        
        The outline should include:
        1. A catchy SEO Title (H1)
        2. Meta Description (150-160 chars)
        3. Excerpt (Brief summary)
        4. Sections (H2 and H3)
        5. FAQ Section
        6. Call to Action (CTA)
        
        Format the response strictly as a JSON object with keys: title, meta_description, excerpt, outline_structure.
        """
        text, error = self._generate_text(prompt)
        if error:
            return None, error
        
        # Extract JSON
        try:
            json_match = re.search(r'\{.*\}', text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group()), None
            return json.loads(text), None
        except Exception as e:
            logger.warning(f"Failed to parse outline JSON: {e}. Raw text: {text}")
            return {
                "title": f"Why {product.name} is the best choice for you", 
                "meta_description": f"Discover why {product.name} is trending in India. Read our full review and buyer guide.", 
                "excerpt": f"An in-depth look at {product.name}.", 
                "outline_structure": text
            }, None

    def generate_full_content(self, product, outline, keywords):
        """Step 3: Generate full blog content."""
        keywords_str = ", ".join(keywords)
        prompt = f"""
        Write a high-quality 1200-word SEO-optimized blog post based on this outline:
        Title: {outline.get('title')}
        Structure: {outline.get('outline_structure')}
        Target Keywords: {keywords_str}
        Product Details: {product.name}, {product.description[:1000]}
        
        Instructions:
        - Use a professional, authoritative, and engaging tone.
        - Naturally integrate the keywords throughout the content.
        - Include internal link placeholders like [PRODUCT_LINK] where a link to the product should be placed.
        - Use Markdown for formatting (bold, bullet points, numbered lists).
        - Add a comprehensive 'Frequently Asked Questions' section at the end.
        - End with a compelling Call to Action to buy from VorionMart.
        
        The content should be helpful, solve customer pain points, and drive sales.
        """
        return self._generate_text(prompt)

    def generate_complete_blog(self, product):
        """Full pipeline to generate a blog from a product."""
        logger.info(f"Starting auto-blog generation for product: {product.name}")
        
        # 1. Keywords
        keywords, error = self.generate_keywords(product)
        if error:
            return None, f"Keyword Gen Failed: {error}"
            
        # 2. Outline
        outline, error = self.generate_outline(product, keywords)
        if error:
            return None, f"Outline Gen Failed: {error}"
            
        # 3. Content
        content, error = self.generate_full_content(product, outline, keywords)
        if error:
            return None, f"Content Gen Failed: {error}"
            
        return {
            "title": outline.get('title', f"Everything you need to know about {product.name}"),
            "content": content,
            "excerpt": outline.get('excerpt', ''),
            "meta_description": outline.get('meta_description', ''),
            "keywords": keywords
        }, None
