import requests
import logging
import json
import re
from django.conf import settings

logger = logging.getLogger('api')

class GeminiBlogService:
    """Service to handle AI blog generation using Google Gemini API."""
    
    def __init__(self):
        self.api_key = getattr(settings, 'GEMINI_API_KEY', None)
        self.model = "gemini-flash-latest"
        self.url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"

    def _generate_text(self, prompt):
        import time
        if not self.api_key:
            return None, "Gemini API Key not configured in settings."

        data = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.7,
                "topK": 40,
                "topP": 0.95,
                "maxOutputTokens": 4096,
            }
        }

        max_retries = 5
        for attempt in range(max_retries):
            try:
                response = requests.post(self.url, json=data, timeout=90)
                
                # Handle 429 Rate Limit with exponential backoff
                if response.status_code == 429:
                    wait_time = min(2 ** attempt * 10, 60)  # 10s, 20s, 40s, 60s
                    logger.warning(f"Gemini API 429 (Rate Limited). Attempt {attempt + 1}/{max_retries}. Retrying in {wait_time}s...")
                    time.sleep(wait_time)
                    continue
                
                # Handle temporary 503 Overload
                if response.status_code == 503:
                    wait_time = min(2 ** attempt * 5, 30)
                    logger.warning(f"Gemini API 503 (Service Unavailable). Attempt {attempt + 1}/{max_retries}. Retrying in {wait_time}s...")
                    time.sleep(wait_time)
                    continue
                
                response.raise_for_status()
                result = response.json()
                
                if 'candidates' in result and result['candidates']:
                    text = result['candidates'][0]['content']['parts'][0]['text']
                    return text, None
                else:
                    return None, f"No content generated by AI: {result}"
            except requests.exceptions.HTTPError as e:
                if response.status_code == 403:
                    logger.error(f"Gemini API 403 Forbidden - API key may be invalid or API not enabled.")
                    return None, "API key is invalid or the Generative Language API is not enabled. Check Google Cloud Console."
                if attempt == max_retries - 1:
                    logger.error(f"Gemini API Error after {max_retries} attempts: {str(e)}")
                    return None, str(e)
                logger.warning(f"Gemini API Attempt {attempt + 1} failed: {str(e)}. Retrying...")
                time.sleep(2)
            except Exception as e:
                if attempt == max_retries - 1:
                    logger.error(f"Gemini API Error after {max_retries} attempts: {str(e)}")
                    return None, str(e)
                logger.warning(f"Gemini API Attempt {attempt + 1} failed: {str(e)}. Retrying...")
                time.sleep(2)
        
        return None, "AI Service is currently busy. Please try again in a few minutes."

    def generate_keywords_and_outline(self, product):
        """Step 1 & 2: Generate SEO keywords and blog outline in one call."""
        prompt = f"""
        Generate a comprehensive SEO plan for a blog post about this product:
        Product Name: {product.name}
        Description: {product.description[:1000]}
        Category: {product.category.name if product.category else 'General'}
        Location: India
        
        Return a JSON object with these keys:
        1. "keywords": A list of 10 high-intent SEO keywords.
        2. "title": A catchy SEO-optimized blog title.
        3. "meta_description": A meta description (150-160 chars).
        4. "excerpt": A brief 2-sentence summary.
        5. "outline_structure": A detailed outline with H2 and H3 sections.
        
        Strictly return ONLY the JSON object.
        """
        text, error = self._generate_text(prompt)
        if error:
            return None, error
        
        # Extract JSON
        try:
            json_match = re.search(r'\{.*\}', text, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group())
            else:
                data = json.loads(text)
            
            # Ensure all keys exist
            if 'keywords' not in data: data['keywords'] = [product.name, "buy " + product.name]
            return data, None
        except Exception as e:
            logger.warning(f"Failed to parse SEO plan JSON: {e}. Raw text: {text}")
            return {
                "keywords": [product.name],
                "title": f"Why {product.name} is the best choice for you", 
                "meta_description": f"Discover why {product.name} is trending in India. Read our full review and buyer guide.", 
                "excerpt": f"An in-depth look at {product.name}.", 
                "outline_structure": text
            }, None

    def generate_full_content(self, product, plan):
        """Step 3: Generate full blog content."""
        keywords_str = ", ".join(plan.get('keywords', []))
        prompt = f"""
        Write a high-quality 1200-word SEO-optimized blog post based on this plan:
        Title: {plan.get('title')}
        Structure: {plan.get('outline_structure')}
        Target Keywords: {keywords_str}
        Product Details: {product.name}, {product.description[:1000]}
        
        Instructions:
        - Use a professional, authoritative, and engaging tone.
        - Naturally integrate the keywords throughout the content.
        - Include internal link placeholders like [PRODUCT_LINK] where a link to the product should be placed.
        - Use Markdown for formatting (bold, bullet points, numbered lists).
        - Add a comprehensive 'Frequently Asked Questions' section at the end.
        - End with a compelling Call to Action to buy from VorionMart.
        
        The content should be helpful, solve customer pain points, and drive sales.
        """
        return self._generate_text(prompt)

    def generate_complete_blog(self, product):
        """Full pipeline to generate a blog from a product."""
        logger.info(f"Starting auto-blog generation for product: {product.name}")
        
        # 1 & 2. Plan (Keywords + Outline)
        plan, error = self.generate_keywords_and_outline(product)
        if error:
            return None, f"Plan Gen Failed: {error}"
            
        # 3. Content
        content, error = self.generate_full_content(product, plan)
        if error:
            return None, f"Content Gen Failed: {error}"
            
        return {
            "title": plan.get('title', f"Everything you need to know about {product.name}"),
            "content": content,
            "excerpt": plan.get('excerpt', ''),
            "meta_description": plan.get('meta_description', ''),
            "keywords": plan.get('keywords', [])
        }, None

